version: "3"

services:
  jongeorge:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    networks:
      - save-a-playlist_web-server

networks:
  save-a-playlist_web-server:
    external: true